TEST-TOUCH-1:
  location: world, 6.900, 62.300, 13.460
  lines:
  - '&AClick here!'
  - '&B&LJOIN NOW!'
TEST-TOUCH-2:
  location: world, 6.900, 62.300, 18.518
  lines:
  - '&AClick here!'
  - '&B&LJOIN NOW!'
