Messages:
  prefix: '&6&lKITS &8» '
  noPermissions: '&8» &cYou don''t have permissions for that.'
  commandCreateError: '&8» &cYou need to use &f/kit create <name>'
  commandDeleteError: '&8» &cYou need to use &f/kit delete <name>'
  commandClaimError: '&8» &cYou need to use &f/kit claim <kit>'
  commandGiveError: '&8» &cYou need to use &f/kit give <kit> <player>'
  commandEditError: '&8» &cYou need to use &f/kit edit <kit>'
  commandPreviewError: '&8» &cYou need to use &f/kit preview <kit>'
  commandOpenError: '&8» &cYou need to use &f/kit open <player> <page>'
  kitAlreadyExists: '&8» &cThe kit &7%name% &calready exists on the config.'
  kitDoesNotExists: '&8» &cThe kit &7%name% &cdoesn''t exists.'
  inventoryEmpty: '&8» &cYou need at least 1 item on your inventory to create a kit.'
  kitCreated: '&8» &7Kit &f%name% &7has &6created &7correctly.'
  kitRemoved: '&8» &7Kit &f%name% &7has &cremoved &7correctly.'
  inventoryName: '&6Kits &7menu'
  kitReceived: '&8» &7Kit &7%name% &7has &areceived.'
  configReload: '&8» &7Plugin &6&lPlayerKits &7has reloaded!'
  seconds: s
  minutes: m
  hours: h
  days: d
  cooldownPlaceholderReady: '&8» &a&lReady!'
  cooldownError: '&8» &cYou need to wait &f%time% &cto claim this kit again.'
  kitNoPermissions: '&8» &cYou don''t have permissions to claim this kit.'
  kitInCooldownLore:
  - '&7You need to wait &c%time%'
  - '&7to claim this kit again.'
  commandList: '&6Kits &7list'
  commandListKit: "&6%number% &8\xc2\xbb &a%kit%"
  commandListKitNoPermissions: "&6%number% &8\xc2\xbb &c%kit% &7(No Permissions)"
  commandListKitInCooldown: "&6%number% &8\xc2\xbb &c%kit% &7(Cooldown: &f%time%&7)"
  commandListKitOneTime: "&6%number% &8\xc2\xbb &c%kit% &7(Already claimed&7)"
  noSpaceError: '&8» &cYou don''t have enough space in your inventory.'
  materialNameError: '&8» &cThere is an error on your config. Material: &7&l%material%
    &cis not valid for your Minecraft version.'
  oneTimeError: '&8» &cYou can''t claim this kit again.'
  kitOneTimeLore:
  - '&7You can''t claim this kit again.'
  previewInventoryName: '&e♛ &aPreview &e♛'
  backItemName: '&e♛ &cBack &e♛'
  playerNotOnline: '&8» &7Player &f%player% &7is &coffline&7.'
  kitGive: '&8» &aKit &7%kit% &agiven to &e%player%&a!'
  noMoneyError: '&8» &cYou don''t have enough money to claim this kit. &8(&a$&c%current_money%&7/&a$&c%required_money%&8)'
  moneyInventoryName: '&e♛ &7Buy this Kit &e♛'
  moneyInventoryYes: '&a&lYES'
  moneyInventoryNo: '&c&lNO'
  moneyInventoryConfirmationName: '&e♛ &aAre you sure? &e♛'
  moneyInventoryConfirmationLore:
  - '&7This will cost you &f$%price%'
  kitInventoryOpen: '&8» &7Opening Kits inventory for &f%player%&7.'
  errorPage: '&8» &cWrite a valid page.'
  commandResetError: '&8» &cYou need to use &f/kit reset <kit> <player>'
  kitResetCorrect: '&8» &7Kit &f%kit% &7has &6reset &7for &f%player%&7!'
  kitResetFail: '&8» &cNot possible to reset kit &f%kit% &cfor &f%player%&c!'
  noPreviewError: '&8» &cThere is nothing to preview for this kit.'
  cantPreviewError: '&8» &cYou can''t preview this kit.'
Config:
  inventorySize: 45
  previewInventorySize: 54
  preview_inventory_back_item_slot: 45
  kit_preview: true
  kit_preview_back_item: true
  hide_kits_with_permissions: false
  close_inventory_on_claim: false
  drop_items_if_full_inventory: false
  commands_before_items: false
  preview_inventory_requires_permission: false
  kit_error_sound: BLOCK_NOTE_BLOCK_PLING;10;0.1
  kit_claim_sound: ENTITY_PLAYER_LEVELUP;10;1.5
  kit_page_sound: BLOCK_LAVA_POP;10;1
  update_notify: true
  player_data_save_time: 300
  mysql_database:
    enabled: false
    host: localhost
    port: 3306
    username: root
    password: root
    database: database
  Inventory:
    '0':
      id: STAINED_GLASS_PANE:15
      name: ' '
    '1':
      id: STAINED_GLASS_PANE:3
      name: ' '
    '7':
      id: STAINED_GLASS_PANE:3
      name: ' '
    '8':
      id: STAINED_GLASS_PANE:15
      name: ' '
    '9':
      id: STAINED_GLASS_PANE:3
      name: ' '
    '17':
      id: STAINED_GLASS_PANE:3
      name: ' '
    '27':
      id: STAINED_GLASS_PANE:3
      name: ' '
    '35':
      id: STAINED_GLASS_PANE:3
      name: ' '
    '36':
      id: STAINED_GLASS_PANE:15
      name: ' '
    '37':
      id: STAINED_GLASS_PANE:3
      name: ' '
    '43':
      id: STAINED_GLASS_PANE:3
      name: ' '
    '44':
      id: STAINED_GLASS_PANE:15
      name: ' '
    '18':
      id: SKULL_ITEM:3
      name: '&6Previous Page'
      skulldata: 2391d533-ab09-434d-9980-adafde4057a3;eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmQ2OWUwNmU1ZGFkZmQ4NGU1ZjNkMWMyMTA2M2YyNTUzYjJmYTk0NWVlMWQ0ZDcxNTJmZGM1NDI1YmMxMmE5In19fQ==
      type: previous_page
    '26':
      id: SKULL_ITEM:3
      name: '&6Next Page'
      skulldata: d513d666-0992-42c7-9aa6-e518a83e0b38;eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTliZjMyOTJlMTI2YTEwNWI1NGViYTcxM2FhMWIxNTJkNTQxYTFkODkzODgyOWM1NjM2NGQxNzhlZDIyYmYifX19
      type: next_page
