settings:
  character: '@'
  format: '&c&lACHAT &8» &f{NAME}: &a{MESSAGE}'
  replaceplaceholdersinmessage: true
  sendmessagestoallservers: true
messages:
  prefix: '&4&lADMINCHAT &8» '
  nopermission: '&cYou don't have permission to that!'
  playeronly: '&cOnly use from players this command!'
  reloaded: '&7Plugin &6&lStaffChat &7has been reloaded!'
  toggled: '&7Chat staff was %s'
  onstring: '&aenabled&7.'
  offstring: '&cdisabled&7.'
discordsrv:
  enable: false
  channel: staffchat
  minecraft-to-discord-format: '{NAME} » {MESSAGE}'
  discord-to-minecraft-format: '&9(Discord) {NAME}: {MESSAGE}'
